name: prime_alert
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.3
  mockito: ^5.4.4
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.5.1
  equatable: ^2.0.7
  go_router: ^14.8.0
  intl: ^0.19.0
  gap: ^3.0.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  bloc_test: ^9.0.3

flutter:
  uses-material-design: true
